repos:
  - repo: local
    hooks:
      - id: llms-generate
        name: Generate llms.txt file
        entry: task
        args: ["llms:generate"]
        language: system
        pass_filenames: false
        always_run: true

      - id: alpine-generate
        name: Generate Alpine.js component JS files
        entry: task
        args: ["alpine:generate"]
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]
      - id: ruff-check
        name: ruff-check-imports
        args: [--select, I, --fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
