# Generated by Django 5.2.16 on 2026-07-28 04:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # `search_name_trgm` below uses gin_trgm_ops, which does not exist until
        # pg_trgm is installed. makemigrations never infers this.
        TrigramExtension(),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("component", "Component"),
                            ("icon", "Icon"),
                            ("block", "Block"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("url", models.CharField(max_length=500)),
                ("weight", models.FloatField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("search_name", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="labbdocs_se_search__956827_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_name"],
                        name="search_name_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("result_count", models.PositiveIntegerField()),
                ("has_results", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["has_results", "created"],
                        name="labbdocs_se_has_res_590b7a_idx",
                    )
                ],
            },
        ),
    ]
