name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  manage-issue:
    uses: ./.github/workflows/community-management.yml
    permissions:
      issues: write
      pull-requests: write
      contents: read
    secrets: inherit
    with:
      item-type: "issue"
      item-number: ${{ github.event.issue.number }}
      author: ${{ github.event.issue.user.login }}
