name: PR Management

on:
  pull_request:
    types: [opened]

jobs:
  manage-pr:
    uses: ./.github/workflows/community-management.yml
    permissions:
      issues: write
      pull-requests: write
      contents: read
    secrets: inherit
    with:
      item-type: "pr"
      item-number: ${{ github.event.pull_request.number }}
      author: ${{ github.event.pull_request.user.login }}
